### ISSUE TITLE
Add open questions Q1 & Q2 to table deck

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Voices#11]

**Comment by lhendey** [comment]
don't merge Q1 Q2 with other responses. give name of Q1/q2 data sets. 
need to specify nonresponse data set?

**Comment by ptatian** [comment]
I will review Q1 and Q2 recodings and add this code for tables.

```
      %Make_one_table( 
        data=Voices.Voices_2017_q1_q2_recode,
        col=&col, 
        colfmt=&colfmt,
        var=Q1_9 Q1_1 Q1_11 Q1_6 Q1_5 Q1_2 Q1_8 Q1_4 Q1_7 Q1_3,
        text="Q1. If someone WHO LIVED IN THE WASHINGTON AREA asked you, where would you say you were from?",
        vlabel=
          Q1_1 = "Washington, DC (or neighborhood within DC)"
          Q1_2 = "Montgomery Co (or place within county)"
          Q1_3 = "Prince George's Co (or place within county)"
          Q1_4 = "Fairfax Co (or place within county)"
          Q1_5 = "Other Northern Virigina (outside Fairfax Co)"
          Q1_6 = "Maryland (no specific place inside region)"
          Q1_7 = "Viriginia (no specific place inside region)"
          Q1_8 = "DMV/Washington region/area/suburbs"
          Q1_9 = "Answered with a place outside DMV"
          Q1_10 = "Multiple categories listed"
          Q1_11 = "Answer did not identify a place"
      )

      %Make_one_table( 
        data=Voices.Voices_2017_q1_q2_recode,
        col=&col, 
        colfmt=&colfmt,
        var=Q2_1 Q2_9 Q2_6 Q2_8 Q2_7 Q2_5 Q2_11 Q2_2 Q2_4 Q2_3,
        text="Q2. If someone WHO LIVED OUTSIDE THE WASHINGTON AREA asked you, where would you say you were from?",
        vlabel=
          Q2_1 = "Washington, DC (or neighborhood within DC)"
          Q2_2 = "Montgomery Co (or place within county)"
          Q2_3 = "Prince George's Co (or place within county)"
          Q2_4 = "Fairfax Co (or place within county)"
          Q2_5 = "Other Northern Virigina (outside Fairfax Co)"
          Q2_6 = "Maryland (no specific place inside region)"
          Q2_7 = "Viriginia (no specific place inside region)"
          Q2_8 = "DMV/Washington region/area/suburbs"
          Q2_9 = "Answered with a place outside DMV"
          Q2_10 = "Multiple categories listed"
          Q2_11 = "Answer did not identify a place"
      )
```

**Comment by lhendey** [comment]
@ptatian i believe stata code should now have vars that are mutually exclusive and account for nonresponses. on commit on branch 11.

**Comment by ptatian** [comment]
@lhendey OK. I was just reviewing this and was going to ask Carl to make some modifications to **Q1 and Q2 recode.do**.  Maybe your changes fixed some of this. 

- I've edited the manual recodings in new files **Q1_recode CGH_PAT.xlsx** and **Q1_recode CGH_PAT.xlsx**. Please substitute these files for the ones you were using previously. 

- Something is not right with the coding of _multi_ and _no_resp_ variables for Q1. There are a number of cases where both = 1. _no_resp_ should indicates responses with no identifiable places mentioned, so it can't be = 1 if anything else is = 1. Similarly...

- For Q2, there are cases where _no_resp_ = 1 but there is another response that is = 1, too. See _caseid_=179, for example. That shouldn't happen. If _no_resp_ = 1 then all other responses should = 0.

- I know I said this before, but I would rather we **not** remove all of the multiple codings from Q1_1-Q1_9 and Q2_1-Q2_9. So, if someone said multiple things, then let's just leave it that way. Let's still keep the Q1_10 and Q2_10 multiple flags, too. (We can always create a version of the variables where people with multiple responses get a 0 for individual responses, but if it's coded that way in the Stata prog then we can't see what the multiple codings are.)

**Comment by lhendey** [comment]
@ptatian - i did do some by hand recoding in stata - would that conflict with any of your recodes in excel? (you should be able to see those recodes pretty easily if you look at the do file in textpad)

Confirming that you now **do not want mutally exclusive categories**...(except for no_resp...) .

**Comment by lhendey** [comment]
@ptatian to clarify on previous comment - not any new by hand recoding today, from before

**Comment by ptatian** [comment]
@lhendey If I understand the Stata code correctly, it looks like the re-codings only get applied to cases where no other coding has been specified (`... if total_list==0 & ...`). So, any manual recodes made in the Excel files should take precedence, is that right?  

Yes, actually, what I'm now thinking is that we have three sets of dummy variables for each of Q1 and Q2.

1. **Qn_1,...,Qn_11**: All places that a person mentioned get coded as 1, allowing multiples. That is, sum of Qn_1,...,Qn_9 can be > 0, in which case, Qn_10 [multi] = 1. Otherwise, Qn_10 = 0. In addition, if Qn_11 [no place in resp] = 1 then all of Qn_1,...,Qn_10 must = 0. Conversely, if any of Qn_1,...,Qn_10 are = 1, then Qn_11 must = 0. 

   - Just to be clear, Qn_11 should not be = 1 if the person gave no answer at all (ie, refused). Qn_11 = 1 only if the person gave an answer but that answer did not include an identifiable place. ("Identifiable place" includes things like "here" that we are interpreting as a location.) All the dummy variables should be missing for cases where the person gave no answer at all. I've added code to the SAS program to account for this. 

2. **uQn_1,...,uQn_11**: Everyone gets _only one_ coded answer, so if sum of Qn_1,...,Qn_9 > 0 then all of uQn_1,...,uQn_9 should = 0 and uQn_10 = 1. (This is what we have now, except for the inconsistencies noted earlier.) Same rules for Qn_11 apply to uQn_11. 

3. **rQn_...**: A series of variables indicating how the answer the person gave (Qn_1,...,Qn_11) corresponds to where they actually live (dov_urban). For each person, do the following _in order until there is a match_, then stop.

   - rQn_none = 1, if the person did not mention any specific place (ie, Qn_11 = 1), otherwise...
   - rQn_same = 1 if the person's answer mentioned _the jurisdiction where they live (dov_urban)_, otherwise...
   - rQn_dc = 1, if the person's answer mentioned _DC_, specifically, otherwise...
   - rQn_oth_juris = 1, if the person's answer mentioned _another jurisdiction in the region_, otherwise...
   - rQn_dmv = 1, if the person's answer mentioned the _Washington area_, otherwise...
   - rQn_md = 1, if the person's answer mentioned _Maryland_, otherwise...
   - rQn_va = 1, if the person's answer mentioned _Virginia_, otherwise...
   - rQn_out = 1, if the person's answer mentioned _a place outside the DMV_.

This could be done in Stata or in the final SAS program but all of the above variables should be included in **Voices.Voices_2017_q1_q2_recode**.

**Comment by lhendey** [comment]
@ptatian - updated stata code to remove part creating mutually exclusive vars.

**Comment by ptatian** [comment]
@lhendey Thanks. We can move **Voices_2017_q1_q2_recode.csv** to Voices\Raw, right? That's where it should be.

**Comment by lhendey** [comment]
@ptatian moved csv to raw.

**Comment by ptatian** [comment]
Just as a note, I changed the coding described above to add a rQn_mult var for people who gave multiple responses. It seemed better than arbitrarily setting a priority order among multiple responses.

**Comment by lhendey** [comment]
@ptatian - i realized that i didn't exchange the recodings in excel as instructed ( e.g. Q1_recode CGH_PAT.xlsx ) Should I do so on a new issue as this is closed?

**Comment by ptatian** [comment]
@lhendey Yes, please.
