### ISSUE TITLE
Add open questions Q15 & Q16 to table deck

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Voices#12]
- [x] Finish recoding data. 

- [x]  add indicators for tables representing all three and top response

**Comment by lhendey** [comment]
@chedman - recoding on branch 12.

**Comment by chedman** [comment]
@ptatian @lhendey Just committed my updates to the Q15 program and synced the changes.

**Comment by lhendey** [comment]
Closing this issue and opening a new one to do actual tables.

**Comment by chedman** [comment]
@lhendey I was able to produce the children break tables locally without issue.
