### ISSUE TITLE
Add variable for single adults with kid(s)

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/Voices#15]

**Comment by lhendey** [comment]
Potentially: 
No kid
Single adult with kid(s)
Multiple adults with kids?
Other?

**Comment by lhendey** [comment]
@chedman  i don't see a branch for this one?

**Comment by chedman** [comment]
@lhendey Did the branch pop up?

**Comment by ptatian** [comment]
Waiting to move forward on other issues since we also need to modify keep statements in various programs.

**Comment by ptatian** [comment]
@chedman Branch develop-#15 has been updated with latest commits from master. Please sync the branch and then continue work this issue. @lhendey

**Comment by chedman** [comment]
@ptatian Sounds good - i'll get started on this issue now.

**Comment by lhendey** [comment]
@chedman to complete #25 as part of this issue.

**Comment by chedman** [comment]
@lhendey I am getting a lot string length errors (see below) when I run the "Voices_q1_q2_recode" file. Also the error "The meaning of an identifier after a quoted string might change in a future SAS release. Inserting white space between a quoted string and the succeeding identifier is recommended.", which hadn't come up before. Did you get these errors?

ERROR: The text expression length (65676) exceeds maximum length (65534). The text expression has been truncated to 65534
       characters.

**Comment by lhendey** [comment]
Closing issue, including #25
