### ISSUE TITLE
Make Q1 and Q2 subquestions mutually exclusive

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/Voices#23]
@chedman  - steps for this issue. 

- [x] Go  back to Q1/Q2 program in stata and edit responses so that any one who said multiple places is also represented in individual response. so can't have dc=1 and multiple=1, etc. That should make it mutually exclusive right?  

- [x] add make break vars macro to Voices_q1_q2_recode.sas.

**Comment by lhendey** [comment]
@chedman - can you wrap this up today? we have more to do.

**Comment by chedman** [comment]
@lhendey Yeah - i'll turn to this now.

**Comment by chedman** [comment]
@lhendey - made the updates. Do you have a second to check in before i commit?

**Comment by chedman** [comment]
@lhendey - just added the pull request
