### ISSUE TITLE
Table modifications

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Voices#25]
@lhendey @chedman Let's keep a running list of basic table modifications that we want to make here. 

- [x] Change title of Q78 table to "Q78. [Persons not born in the U.S. (Q77)] Are you...?"
- [x] Change title of Q62 table to "Q62. [Persons not currently working (Q59)] Are you currently...
- [x] Change title of Q63a-g tables to "Q63a-g. [Persons currently looking for work (Q62)] How important...
- [x] change title of q60 to "Q60. [Persons currently working (Q59)] How strongly..."
- [x] change title of q61 to "Q61. [Persons currently working (Q59)] Does your current..."
- [x] change title of Q23 to "Q23. [Persons who never used nonprofit services (Q22)] Why do you never..."
- [x] change title of Q24 to "Q24. [Persons who used nonprofit services (Q22)] How satisfied..."

**Comment by lhendey** [comment]
@chedman to take care of these changes on #15

**Comment by lhendey** [comment]
Closing issue, changes made on #15
