### ISSUE TITLE
Prep for final VoicesDMV survey data

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Voices#3]
Do work here preparing programming for final VoicesDMV survey data.

**Comment by lhendey** [comment]
@chedman - please make sure you are using github for your programming. let me know if it would be helpful to check in now that we have the final data!

**Comment by chedman** [comment]
@lhendey ok great! Yeah, it may be helpful to check in later this afternoon if you are around to make sure I am going through the right github process.

**Comment by ptatian** [comment]
@chedman @lhendey I'll be doing some work looking at recoding the open-ended responses. Decided it made sense to just do that work under this same issue.

**Comment by ptatian** [comment]
@chedman @lhendey I've created a basic program (D:\DCData\Libraries\Voices\Prog\Voices_tables.sas) that can be used to generate the survey tables using SAS. The program applies the design effect correction to create the proper standard errors. 

I've done a few questions as examples, but, Carl, you should be able to add to this program for the other questions. For testing purposes, you can adjust the OBS= parameter to a smaller value, like 100.

`  set Voices.VoicesDMVSurvey2017 (OBS=100000);  ** Make the OBS= value smaller for testing **;`

You will need to do the recording of question vars in the first data step. If there are other variables with 1,2,-1 values, then they can just be added to the array with the Q13 vars. 

```
  ** Recode questions with 1,2,-1 response codes **;

  array v12{*} Q13: ;
```

Note that I'm using the SAS **:** wildcard for variable names. **Q13:** matches all variables that start with Q13. 

For other types of recoding, you'll have to add new code. It might be helpful to look at the other SAS programs I wrote in the Prog folder for dealing with specific questions. 

I've created separate data sets for the design effect values for the region as a whole and for the jurisdiction breakouts (geo). You must add the remaining design effect data sets for the other breaks. 

** Create data sets with design effect corrections **;

```
data DEFF_region;

  input region deff;

  datalines;
  1 1.422
  ;

run;
```

I use two macros to generate the individual tables. The general appearance of the tables is set in the _%Make_one_table()_ macro. So, if we want to make adjustments to how the tables look, we can do that in this macro. 

In the _%Make_all_tables()_ macro, you need to add the names of any question variables to be used in the tables to the macro var list. Again, you can use the : wildcard to refer to a series of variables. 

```
  ** List all of the variables to be used in the tables here **;

  %let full_var_list = 
    Q3_Years_months_recode Q4_Years_months_recode Q5_Years_months_recode
    Q13:
  ;
```

You then need to add individual tables to this macro by adding separate invocations of the _%Make_one_table()_ macro. The first parameter (_col=&col,_) is always the same. The _fmt=_ parameter lets you override the default format, which is for percents. So, if your table is percents you can just omit _fmt=_. Finally, list the variables that will define the table rows in the _var=_ parameter, and add the question text (in quotes) to the _text=_ parameter. 

```
  %Make_one_table( 
    col=&col, 
    fmt=comma10.1,
    var=Q3_Years_months_recode Q4_Years_months_recode Q5_Years_months_recode, 
    text="How long have you lived in..." 
  )

  %Make_one_table( 
    col=&col, 
    var=Q13:, 
    text="Q13. Have you, yourself, done any of the following in the last 12 months?" 
  )
```

At the end of the program, you'll see how I invoke the main _%Make_all_tables()_ macro for the different breaks that we want. You'll need to add other breaks as they are ready. 

```
** Create tables **;

%Make_all_tables( col=region, title=Tables for Entire Region )
%Make_all_tables( col=geo, title=Tables by Jurisdiction )
```

Output is written to RTF files, which can be read in Word. You can see the ones I created to this point here.

L:\Libraries\Voices\Prog\Voices_tables_geo.rtf
L:\Libraries\Voices\Prog\Voices_tables_region.rtf

I hope that makes sense. Please take a look at the program and let me know if you have any questions.

**Comment by ptatian** [comment]
@chedman @lhendey I have something for the Q1 & Q2 recoding now. I've placed these files on L:

L:\Libraries\Voices\Raw\Q1_recode.csv
L:\Libraries\Voices\Raw\Q2_recode.csv

Each file has a row for one or more entities from the Q1 and Q2 responses and a preliminary flagging of them as referring to the District (DC), Montgomery Co (MC),Prince George's (PG), Fairfax County (FC), Northern Virginia (NV),  or somewhere/something else (OT). **It would be good for someone to scan through these and see if they make sense. @chedman, would you be able to do that?** 

The idea would be to manually edit any that are off. Also, sometime people refer to DC neighborhoods and I didn't try to automatically recode those so they would need to be done by hand. If it makes sense we can add certain neighborhoods to the automatic coding, but it may not be worth it. 

Finally, if an entity is coded as "OT," but doesn't represent a **place**, I think we should delete the "X" for "OT." 

At the end, these would need to be matched back to the survey data (by caseid) and we can do tables for people who say they are from somewhere different than where they live, for instance. Perhaps down the road we can do something more sophisticated but that seems like a reasonable first step. 

Let me know if you have questions or comments.

**Comment by chedman** [comment]
@ptatian @lhendey Hi Peter, sorry the notification didn't end up in my inbox for some reason. I could take a look into this on Monday if that is alright?

**Comment by ptatian** [comment]
Yes, that’s fine. Check your spam filters. I had some problems with messages from GitHub ending up in spam before.

**Comment by ptatian** [comment]
@lhendey @chedman I'm taking a look at open-ended questions 15 and 16 now.

**Comment by ptatian** [comment]
@lhendey @chedman Made a few changes to update/streamline some things. 

- Original GfK file is now registered with metadata (**Voices.Voicesdmvsurvey2017**).
- Created **Make_formats.sas** program to save permanent formats for recoded questions. 
- Split **Voices_tables.sas** into two programs
  - **Voices_nonopen_recode.sas** saves the recoded nonopen question responses as a permanent data (**Voices.Voices_2017_nonopen_recode**). I moved the code to create the break variables to a macro, _%Make_break_vars_2017()_, to make it easier to reuse in creating the separate files that will have the open responses. 
  - **Voices_tables.sas** now just creates the tables. I revised the formatting of the tables so that the columns are now in the correct order, removed the % signs from all the numbers (column header now says "Pct." for those tables), and moved the titles and footnotes to the body of the document. I also moved the code to create the sample design effect data sets to a macro. 
- The tables now use a new custom ODS style Styles.Voices_style_rtf. Before running the tables, you need to create this style by submitting the **Voices_style_rtf.sas** program. You only need to do this once and the new style will be permanently saved to your SAS setup. (Of course, you need to resubmit if we change the style.) 
- Reran all the tables and saved to L: and [Box](https://urbanorg.app.box.com/folder/38116193435).

**Comment by ptatian** [comment]
@lhendey @chedman We should plan to close this issue and merge changes after the data walk. We can open new issues for further changes and survey analysis for the final report.

**Comment by ptatian** [comment]
@lhendey @chedman Are there any outstanding loose ends on the survey analysis that we should tie up before closing this issue? I recognize there's still more work to do, but I would prefer to create new issues for the follow on work for the final analysis. Please let me know, however, if there's anything you are working on that we should wrap up first. Thanks.
