### ISSUE TITLE
Create tables for jurisdictional deep-dive analysis

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Voices#48]
Create tables for 5 jurisdictional briefs for DC, PG, MoCo, Fairfax Co, and NoVa. 
Charge code is 101476-0001-001.

**Comment by ptatian** [comment]
Adding @lhendey to the conversation for this issue.

**Comment by lhendey** [comment]
@maggiesu0725 

Convert sas data set to stata: Voices_2017_nonopen_recode – save in L:\Libraries\Voices\Data

merge on replicate weights with L:\Libraries\Voices\Raw\VoicesDMVSurvey2017_replicatewts  by caseid (should go with format of caseid on sas file).  

don't overwrite the Voices_2017_nonopen_recode file

**Comment by lhendey** [comment]
@maggiesu0725 - i'm not sure this is helpful but this do file had my attempts at the mata code - (obviously now not with the svy procedures you need) https://github.com/NeighborhoodInfoDC/Voices/blob/master/Prog/Test%20prog%20for%20means.do

**Comment by maggiesu0725** [comment]
@lhendey I tested the code and it should be generating the right tables for t-test now.

**Comment by lhendey** [comment]
@maggiesu0725 - did you sync all changes? I'm getting an error.

**Comment by maggiesu0725** [comment]
@lhendey   I synced all changes. What's the error? I can debug later today.

**Comment by lhendey** [comment]
@maggiesu0725 - it was missing the punctuation around the '`var''  - I did replace a variable and reorder the list of variables (q21 and q35) so they'd be in a better order in the output so you should sync and rerun - changed the output to the prog folder. Go ahead and start working on the formatting and significance testing in the tables.

**Comment by maggiesu0725** [comment]
@lhendey I updated the program to generate the right sub-population for t-test, the tables is here: L:\Libraries\Voices\Tables\5 jurisdictions brief , I will go ahead and calculate the t statistics

**Comment by lhendey** [comment]
@maggiesu0725 - this code looks fine.

**Comment by ptatian** [comment]
Was a pull request ever done for this? We should do a pull request, review, and finalize this issue. If modifications are needed later, we will open a new issue.
