### ISSUE TITLE
Create new permanent data set with recoded responses to open questions Q15

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Voices#7]

**Comment by lhendey** [comment]
Original Response, Key Words and recoded variable. - Merge back in original responses. 

Structure of file: Multiple rows per respondent (3 rows) and then a response can have multiple key words.

**Comment by lhendey** [comment]
@ptatian  - i assume you want some review of the coding of  q15 and 16 vars - to what extent do you want me to code things that didn't have anything assigned via the google NPL process?

**Comment by ptatian** [comment]
Really I was expecting Carl to review those codings. That was the idea of this (or rather the previous) task. 

That should have included things that didn't get coded at all. To what extent did that happen?

**Comment by lhendey** [comment]
@ptatian - for things not initially recoded via NPL - do i need to worry about the "Entity" variable? I'm assuming i just assign one of the existing categories if relevant.

**Comment by ptatian** [comment]
@lhendey You do not need to worry about the Entity var. That's just to get us to the categories.

**Comment by lhendey** [comment]
@ptatian it looks like on Voices_q15_recode.sas if multiple words were captured you decided to take a random word - so for one observation "Accessibility to the Smithsonians" returns "Location" and "Museums" but Location  was randomly selected. So it seems fixing the order in Python wouldn't matter. 

So - we could keep the random to deal with multiple things but maybe giving some things priority? Like code only code location if there isn't another thing?

**Comment by ptatian** [comment]
@lhendey Oh yes, you are right. It was random. Agree with keeping random but with priorities.

**Comment by ptatian** [comment]
@lhendey The order in Python only affects how a particular entity gets recoded, that is, whether "accessibility" gets recoded to "location" or something else.

**Comment by lhendey** [comment]
@ptatian - public transit is in "Metro" and public transportation is in "transportation" - move public transportation to Metro?

**Comment by ptatian** [comment]
Well, we have other public transit than Metro, so I think that's why I didn't do it that way. I didn't want poor Metro to be blamed if people are unhappy about DASH or something else.
